### ISSUE TITLE
Hitomi Stats V5 broken

### ISSUE THREAD

**Issue by Lunethia** [MiraiSubject/awesome-osu-tournaments#18]
Dunno where else to put this but when opening HitmoiChan's StatsV5 sheet I get to see the following (See image)
![Screenshot_13](https://github.com/MiraiSubject/awesome-osu-tournaments/assets/52287610/13b20593-4368-4862-80d2-eb82d405d84e)

Not that you can do anything about it, but yeah.
No way of contacting Hitomi either since the Discord mentioned on the sheet doesn't exist and they don't accept DMs in Osu! from non-friends.

**Comment by itsmehoaq** [comment]
Made this while we wait for a proper fix.
[here](https://docs.google.com/spreadsheets/d/10sU3V-1pWImnzQ0IQDZ1y9Y8R5iBkEPbMKGdOIAsHcw/edit?usp=sharing)

**Comment by Lunethia** [comment]
Yo wtf hoaq you are the GOAT
